filter:
  excluded_paths:
    - vendor/*
    - tests/*

checks:
  php:
    code_rating: true
    duplication: true
    remove_extra_empty_lines: true
    remove_trailing_whitespace: true

before_commands:
  - "composer install --prefer-source"
  
tools:
  external_code_coverage: true
