language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction